version: '2'

services:
  apacheds:
    build:
     context: .
     dockerfile: Dockerfile
    restart: always
    image: greggigon/apacheds
    ports:
    - "10389:10389"
    command:
      - --loglevel warning
    volumes:
    - apacheds_data_vol:/data:Z
    - apacheds_bootstrap_vol:/bootstrap:Z
    environment:
    - BOOTSTRAP_FILE=/bootstrap/bootstrap-data-in-apacheds.ldif
    - DEBUG=false
volumes:
  apacheds_bootstrap_vol:
    external: true
  apacheds_data_vol:
    external: true
