version: '2'

services:
  apacheds:
    restart: always
    image: greggigon/apacheds
    ports:
    - "10389:10389"
    command:
      - --loglevel warning
    volumes:
    - /apacheds_bootstrap_vol:/bootstrap:Z
    environment:
    - DEBUG=false
volumes:
  apacheds_bootstrap_vol:
    external: true
